#!/usr/bin/env bash
#
# This script supports testing by generating a file for uploading into an S3 bucket that can subsequently be
# downloaded by the app to test concurrency performance characteristics. The script generates a specified sized
# file, filled with repetitive text "n bytes n bytes..." where 'n' is the size specified on the command line.
#
# Usage
#
# ./genfile [filename] [bytes]
#
# E.g.:
#
# ./genfile 100000-bytes 100000
#
# Results in a file named '100000-bytes' filled with content "100000 bytes 100000 bytes 100000 bytes..." having
# size exactly 100,000 bytes.
#

filename=$1
size=$2
content=$(printf "%s bytes" $2)
content_len=${#content}

written=0

while [[ $written -lt $size ]]; do
  echo -n "$content" >> "$filename"
  if [[ $written -eq 0 ]]; then
    content=" $content"
  fi
  written=$((written + content_len))
done

truncate -s $size "$filename"
